services:

  clothing-model:
    build:
      context: .
      dockerfile: image-model.dockerfile
    ports:
      - 8500:8500

  gateway:
    build:
      context: .
      dockerfile: image-gateway.dockerfile
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - 9696:9696